name: environment
channels:
  - pyviz
  - anaconda
  - conda-forge
  - defaults
dependencies:
 - numpy
 - holoviews
 - xarray
 - glob
 - pathlib
 - pandas
 - panel
 - bokeh
 - scipy.stats
 - hvplot.xarray